name: Deploy client

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm -F client install

      - name: Build
        run: pnpm -F client build
        env:
          VITE_AUTH_URI: ${{ secrets.VITE_AUTH_URI }}
          VITE_AUTH_KEY: ${{ secrets.VITE_AUTH_KEY }}
          VITE_ADMIN_AUTH_KEY: ${{ secrets.VITE_ADMIN_AUTH_KEY }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          folder: client/dist
